module "wrapper" {
  source = "../../modules/file-system"

  for_each = var.items

  accept_bucket_warning          = try(each.value.accept_bucket_warning, var.defaults.accept_bucket_warning, null)
  access_points                  = try(each.value.access_points, var.defaults.access_points, {})
  bucket_arn                     = try(each.value.bucket_arn, var.defaults.bucket_arn)
  bucket_versioning_status       = try(each.value.bucket_versioning_status, var.defaults.bucket_versioning_status)
  create                         = try(each.value.create, var.defaults.create, true)
  create_iam_role                = try(each.value.create_iam_role, var.defaults.create_iam_role, true)
  create_security_group          = try(each.value.create_security_group, var.defaults.create_security_group, true)
  iam_role_arn                   = try(each.value.iam_role_arn, var.defaults.iam_role_arn, null)
  iam_role_description           = try(each.value.iam_role_description, var.defaults.iam_role_description, null)
  iam_role_name                  = try(each.value.iam_role_name, var.defaults.iam_role_name, null)
  iam_role_path                  = try(each.value.iam_role_path, var.defaults.iam_role_path, null)
  iam_role_permissions_boundary  = try(each.value.iam_role_permissions_boundary, var.defaults.iam_role_permissions_boundary, null)
  iam_role_tags                  = try(each.value.iam_role_tags, var.defaults.iam_role_tags, null)
  iam_role_use_name_prefix       = try(each.value.iam_role_use_name_prefix, var.defaults.iam_role_use_name_prefix, true)
  kms_key_id                     = try(each.value.kms_key_id, var.defaults.kms_key_id, null)
  mount_targets                  = try(each.value.mount_targets, var.defaults.mount_targets, {})
  name                           = try(each.value.name, var.defaults.name, null)
  policy_statements              = try(each.value.policy_statements, var.defaults.policy_statements, null)
  prefix                         = try(each.value.prefix, var.defaults.prefix, null)
  region                         = try(each.value.region, var.defaults.region, null)
  security_group_description     = try(each.value.security_group_description, var.defaults.security_group_description, null)
  security_group_egress_rules    = try(each.value.security_group_egress_rules, var.defaults.security_group_egress_rules, {})
  security_group_ingress_rules   = try(each.value.security_group_ingress_rules, var.defaults.security_group_ingress_rules, {})
  security_group_name            = try(each.value.security_group_name, var.defaults.security_group_name, null)
  security_group_tags            = try(each.value.security_group_tags, var.defaults.security_group_tags, null)
  security_group_use_name_prefix = try(each.value.security_group_use_name_prefix, var.defaults.security_group_use_name_prefix, true)
  security_group_vpc_id          = try(each.value.security_group_vpc_id, var.defaults.security_group_vpc_id, null)
  security_groups                = try(each.value.security_groups, var.defaults.security_groups, null)
  synchronization_configuration  = try(each.value.synchronization_configuration, var.defaults.synchronization_configuration, null)
  tags                           = try(each.value.tags, var.defaults.tags, {})
  timeouts                       = try(each.value.timeouts, var.defaults.timeouts, null)
}
